dappx/urls.py
from django.conf.urls import url

from .views import RegisterView, LoginView, IndexView, DetailView, ResultsView
from . import views

app_name = 'dappx'

urlpatterns = [
    url(r'^index/$', IndexView.as_view() ,name = 'index'),
    url(r'^register/$', RegisterView.as_view(), name = 'register'),
    url(r'^user_login/$', LoginView.as_view(), name = 'user_login'),
    url(r'^(?P<pk>[0-9]+)/$', DetailView.as_view(), name = 'detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', ResultsView.as_view(), name = 'results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name = 'vote'),

]

dropjx/urls.py
from django.contrib import admin
from django.urls import path, include
from dappx import views as v
from django.conf.urls import url


urlpatterns = [
    path('admin/', admin.site.urls),
    path('dappx/',include('dappx.urls')),
    url(r'^logout/$', v.user_logout, name='logout'),

]

dappx/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.utils import timezone




# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    

class Question(models.Model):
    objects = None
    question_text = models.CharField(max_length = 200, verbose_name = "Polling question")
    pub_date = models.DateTimeField(verbose_name = "date published")


    def __str__(self):
        return self.question_text


    def was_published_recently(self):
        now = timezone.now()
        #return now - datetime.timedelta(days = 1) <= self.pub_date <= now

        return now - datetime.timedelta(days = 1) <= self.pub_date <= now


class Choice(models.Model):

    DoesNotExist = None
    choice_text = models.CharField(max_length = 200)
    vote = models.IntegerField(default = 0)
    question = models.ForeignKey(Question,on_delete = models.CASCADE)

    def __str__(self):
        return self.choice_text

dappx/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')

dappx/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render
from django.views import View
from django.contrib.auth.decorators import login_required
from .forms import UserForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .models import UserProfileInfo, Question, Choice
from django.utils import timezone
from django.views import generic


# Create your views here.

#@login_required Use comment when testing test cases, otherwise uncomment it before firing server
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('dappx:index'))

#@method_decorator(login_required)
class IndexView(View):
    template_name = 'dappx/index.html'  # the template to load through this view

    def get(self, request, *args, **kwargs):



            latest_question_list = Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

            return render(request, self.template_name, {'latest_question_list': latest_question_list})




class DetailView(generic.DetailView):
    model = Question
    template_name = 'dappx/detail.html'
    context_object_name = 'question'



class ResultsView(generic.DetailView):
    model = Question
    template_name = 'dappx/result.html'
    context_object_name = 'question'





def vote(request,question_id):
    if(request.method == "POST"):
        question = Question.objects.get(pk = question_id)
        try:
            selected_choice = question.choice_set.get(pk = request.POST['choice'])
        except(KeyError, Choice.DoesNotExist):
            return render(request, 'dappx/detail.html',
                          {'question': question, 'error_message': "you didn't select a choice", })
        else:
            selected_choice.vote += 1
            selected_choice.save()

        return HttpResponseRedirect(reverse('dappx:results', args = (question.id,)))







class RegisterView(View):
    user_form = UserForm
    template_name = 'dappx/registration.html'

    def get(self, request, *args, **kwargs):
        user_form = self.user_form()
        return render(request, self.template_name,{'user_form':user_form,})


    def post(self, request, *args, **kwargs):

        registered = False
        user_form = self.user_form(request.POST)


        if(user_form.is_valid):
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
        else:
            pass

        return render(request,self.template_name,{'registered':registered, 'user_form':user_form,})



class LoginView(View):
    template_name = 'dappx/login.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})

    def post(self,request, *args, **kwargs):
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username= username, password= password)


        if(user):

            login(request,user)
            return HttpResponseRedirect(reverse('dappx:index'))

        else:
            return HttpResponse("Someone tried to login and failed. They used username: {} and password: {}".format(username,password))

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'dappx:index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'dappx:register' %}">Register</a></li>
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'dappx:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/dappx/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}

    {{ error_message }}

{% endif %}







  <form method = "post" action = "{% url 'dappx:vote' question.id %}">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}

            <input type = "radio" name = "choice" value = "{{ choice.id }}" id = "choice{{ forloop.counter }}">
            <label for = "choice{{ forloop.counter }}">{{choice.choice_text}} ({{ choice.vote }})</label>

        <br>

        {% endfor %}
        <input type = "submit" value = "Vote">

    </form>
<a href="{% url 'dappx:index' %}">Go to College list</a>










<!--<form action = "{url 'example_poll:vote' question.id}" method = "post">
    {% csrf_token %}


</form>

-->

templates/dappx/index.html
{% extends 'base.html' %}
{% block body_block %}
<div>
<h1 align ="center">Polling application</h1>

{% if user.is_authenticated %}



<hr>

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'dappx/style.css' %}">


<p>Welcome, <b>{{ user.username }}</b>. This is simple polling
application where you can vote for participants for any
of the listed college</p>



   


<p>&nbsp;</p>
<p>&nbsp;</p>
{% if latest_question_list %}


   {% for question in latest_question_list %}
    <p style = "text-align:center"><b>Voting lines</b> open from {{ question.pub_date }}
       </p>

{% if question.choice_set.all %}
<div class = "gniot">


             <a href = "{% url 'dappx:detail' question.id %}">{{question.question_text}}</a>({{ question.choice_set.count }} <b>choice</b>{{ question.choice_set.count|pluralize }})

</div>
{% else %}
<div class = "gniot">
            <b>{{ question.question_text }} </b>(No choice)

</div>
{% endif %}

{% endfor %}

{% endif %}
    {% else %}
    <h2>Please <a href = "{% url 'dappx:user_login' %}">Login</a> here</h2>

{% endif %}
</div>
{% endblock %}




<br>
<br>

templates/dappx/login.html
{% extends 'base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'dappx:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

templates/dappx/registration.html
{% extends "base.html" %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}

          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/dappx/result.html
<html>
<head>
    <style>



    </style>
</head>
<body>

{% load static %}

<link rel = "stylesheet" type = "text/css" href = "{% static 'dappx/style.css' %}">

<div class = "result">

<h2>{{question.question_text}}</h2>


{% for choice in question.choice_set.all %}

    <p>{{ choice.choice_text  }} ---->  {{ choice.vote }}</p>


{% endfor %}


 </div>
<br>
<div style = "text-align:center;"><a href="{% url 'dappx:detail' question.id %}">Wanna vote again </a>
<p>or</p>
    <a href="{% url 'dappx:index' %}">Go to College list</a>
</div>


</body>
</html>